export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const IS_LOADING = 'IS_LOADING';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_FAILURE = 'SIGNIN_FAILURE';
export const SET_PROFILE = 'SET_PROFILE';
export const LOGOUT_USER = 'LOGOUT_USER';
export const GET_PROFILE_ERROR = 'GET_PROFILE_ERROR';

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";
